# TOP script

import zmq_manager
import numpy as np


def onCook(scriptOp):
    q = zmq_manager.output_q

    if not q.empty():
        # Pull the processed frame from the global queue
        processed_frame = q.get()

        # Convert uint8 -> float32 for TD
        img_float = processed_frame.astype(np.float32) / 255.0
        scriptOp.copyNumpyArray(img_float)
    else:
        # Keep current image or scriptOp.clear()
        pass


def onSetupParameters(scriptOp):
    """Auto-generated by Component Editor"""
    # manual changes to anything other than parJSON will be	# destroyed by Comp Editor unless doc string above is	# changed

    TDJSON = op.TDModules.mod.TDJSON
    parJSON = """
	{
		"Custom": {
			"Cooktrigger": {
				"name": "Cooktrigger",
				"tupletName": "Cooktrigger",
				"label": "cookTrigger",
				"page": "Custom",
				"sequence": null,
				"style": "Float",
				"size": 1,
				"defaultMode": "CONSTANT",
				"default": 0.0,
				"defaultExpr": "",
				"defaultBindExpr": "",
				"enable": true,
				"startSection": false,
				"readOnly": false,
				"enableExpr": null,
				"help": "",
				"min": 0.0,
				"max": 1000.0,
				"normMin": 0.0,
				"normMax": 1000.0,
				"clampMin": false,
				"clampMax": false
			}
		}
	}
	"""
    parData = TDJSON.textToJSON(parJSON)
    TDJSON.addParametersFromJSONOp(scriptOp, parData, destroyOthers=True)
